### ISSUE TITLE
Auto purger not working

### ISSUE THREAD

**Issue by sanjayvattikonda** [n-raghu/ezDBA#3]
Received disk full error because auto purger could not delete legacy backup sets.

Traceback (most recent call last):
  File "dtsAdmin.py", line 147, in <module>
    rerun=backupJOB(bst,ret,backup_path)
  File "dtsAdmin.py", line 58, in backupJOB
    ss=backupAgent(bkCFG,bkpacks,dbTuple)
  File "/var/www/html/dts/DTS_Packs/backupManager.py", line 40, in backupAgent
    cbk=createBackup(opsTMP,path,backupSetID)
  File "/var/www/html/dts/DTS_Packs/backupManager.py", line 68, in createBackup
    tmp.write(str(ops))
IOError: [Errno 28] No space left on device

**Comment by n-raghu** [comment]
code updated and now working as expected
